# Generated by Django 5.2.4 on 2025-07-22 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income_expense', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.business'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income_expense.category'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
