# Generated by Django 5.2.4 on 2025-07-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=5)),
                ('app_lock', models.BooleanField(default=False)),
                ('ai_alerts', models.BooleanField(default=True)),
                ('finance_tips', models.BooleanField(default=True)),
                ('multi_business', models.BooleanField(default=False)),
                ('calendar_view', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
