# Generated by Django 5.2.4 on 2025-07-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udhari', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='udhari',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udhari.customer'),
        ),
    ]
